name: Deploy a GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Clone the repository
        uses: actions/checkout@v3

      - name: Setup Ruby for Jekyll
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install

      - name: Build with Jekyll
        run: bundle exec jekyll build --config _config.yml,_config_prod.yml

      - name: Create config.json inside _site/assets
        run: |
          mkdir -p ./_site/assets
          echo '{
            "apiKey": "${{ secrets.FIREBASE_API_KEY }}",
            "authDomain": "${{ secrets.FIREBASE_AUTH_DOMAIN }}",
            "projectId": "${{ secrets.FIREBASE_PROJECT_ID }}",
            "storageBucket": "${{ secrets.FIREBASE_STORAGE_BUCKET }}",
            "messagingSenderId": "${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}",
            "appId": "${{ secrets.FIREBASE_APP_ID }}",
            "measurementId": "${{ secrets.FIREBASE_MEASUREMENT_ID }}"
          }' > ./_site/assets/config.json

      - name:  Confirm config.json exists
        run: |
          echo "Verifying config.json in _site/assets/"
          if [ -f "./_site/assets/config.json" ]; then
            echo " config.json found:"
            cat ./_site/assets/config.json
          else
            echo " config.json not found!"
            exit 1
          fi

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
